### PR TITLE
fix: try to fetch default branch programmatically

### LINKED ISSUE #18: Non-master default branches
Github is [in the process](https://github.com/github/renaming) of switching to using `main` as the default for a default branch. This breaks with semtag as there are [some occurrences](https://github.com/pnikosis/semtag/search?q=master) of hard-coding `master` in the code.

The default branch can be retrieved programmatically using `git symbolic-ref refs/remotes/origin/HEAD | sed "s@^refs/remotes/origin/@@"`.

### PR DESCRIPTION
**Pull request by apriljo**
Attempt to fetch the default branch programmatically. Otherwise, default to current assumption of `master`.

Fixes #18

### CODE REVIEW

**Comment by nico2sh** [comment]
Weird enough, I'm getting `develop` as the default branch. Something I'm missing, will double check and merge if I figure out what's wrong

**Comment by apriljo** [comment]
As far as I can tell the symbolic-ref of the remote head is added when the remote is configured (likely when you cloned). If you change it in your repo's github's settings after cloning you may need to run `git remote set-head origin --auto` to update your local clone.

**Comment by nico2sh** [comment]
Yeah, I tried `git remote set-head origin --auto` but I'm still getting `develop` as default branch.

What about `git symbolic-ref --short HEAD`? I tested it that one and works correctly here.

**Comment by nico2sh** [comment]
OK, found the issue on my side, thanks for the update, merging!

**Pull request merged**
